name: Run Lighthouse

on:
  push:
    branches:
    - gh-pages
    - main
jobs:
  validate-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lighthouse CI Action
      uses: treosh/lighthouse-ci-action@v2
      with:
        urls: |
          https://cdcgov.github.io/SimpleReport_Public_Site/
        uploadArtifacts: false
        configPath: ./lighthouse/lighthouserc.yml
        runs: 1
